### ISSUE TITLE
Question: Is it possible to use stylegan2(-ada) models with stylegan3?

### ISSUE THREAD

**Issue by Randy-H0** [NVlabs/stylegan3#1]
I know that this form is ment for bug reports but I currently can't find another way to ask.

Is it possible to use stylegan2-ada(-pytorch) models with stylegan3 and expect decent results or do I need to fully retrain the model?

If I do need to retrain the model, is there a way to make it augment the dataset like stylegan2-ada? If there is a way to do that, could you please provide me on how to do that?

Thanks so much! I'm sure this is going to be awesome 😉😉

**Comment by Randy1435** [comment]
Again, I'm very sorry for putting this question here but I couldn't put it anywhere else.
