### ISSUE TITLE
Training stylegan3 on non-square images

### ISSUE THREAD

**Issue by Randy1435** [NVlabs/stylegan3#118]
Is it possible to train stylegan3 on non-square images? (for example, 1280 x 720. 1920 x 1080)
And then generate images?

**Comment by botoxparty** [comment]
Works fine for me if I just add white space and crop it as a square. This technique has been successful since the first version of stylegan.

**Comment by Randy1435** [comment]
> Works fine for me if I just add white space and crop it as a square. This technique has been successful since the first version of stylegan.

Works for me! Thanks

**Comment by msseibel** [comment]
You all have probably moved on, but do you know if somebody has worked on this?
