### ISSUE TITLE
Any plans on releasing the pretrained model on the beaches dataset?

### ISSUE THREAD

**Issue by yj7082126** [NVlabs/stylegan3#12]
Hi, 
I was impressed by the model mimicing the camera movements when trained on the Beaches dataset, 
and it seems the only pretrained model weights available now are ffhq, afhq, and metfaces.
Is there any future plans involving releasing the model weights for the Beaches dataset?

Thanks.

**Comment by betterze** [comment]
@jannehellsten Thank you for the explaination. Is there any pretrained model for natural scene? Maybe mountain, lake?
