### ISSUE TITLE
Training stylegan3 on colab

### ISSUE THREAD

**Issue by Randy1435** [NVlabs/stylegan3#120]
Is it possible to train stylegan3 on google colab using google's T4's? If so, is there a notebook?

**Comment by botoxparty** [comment]
Here's a link to a notebook on colab:

https://colab.research.google.com/drive/1Nal3M-wjv6BeIgyTgvxhaccPFGEP6cbk?usp=sharing

And the article that the author wrote to go alongside it:

https://levelup.gitconnected.com/training-a-stylegan3-in-colab-gan-create-nft-6dd119774644

I've seen the following table regarding Google Colab performance for stylegan but can't confirm/deny how accurate it is:

V100 = Excellent (*Available only for Colab Pro users*)
P100 = Very Good
T4 = Good (*preferred*)
K80 = Meh
P4 = (*Not Recommended*)

**Comment by Randy1435** [comment]
> Here's a link to a notebook on colab:
> 
> https://colab.research.google.com/drive/1Nal3M-wjv6BeIgyTgvxhaccPFGEP6cbk?usp=sharing
> 
> And the article that the author wrote to go alongside it:
> 
> https://levelup.gitconnected.com/training-a-stylegan3-in-colab-gan-create-nft-6dd119774644
> 
> I've seen the following table regarding Google Colab performance for stylegan but can't confirm/deny how accurate it is:
> 
> V100 = Excellent (_Available only for Colab Pro users_) P100 = Very Good T4 = Good (_preferred_) K80 = Meh P4 = (_Not Recommended_)

Thanks! The table is decently accurate. I think the P100s are slower in training compared to T4s. Because t4s are made for fast inference but this does also increase speed. I once tried training on a K80 and it sucks, a lot

**Comment by AlexanderKozhevin** [comment]
@Randy1435 @botoxparty 
Hello. Sorry, can you advise any refence for giuded generation? It ok to create random image, but what if I want it to be similar to smth. For image restoration for example?
