### ISSUE TITLE
HELP. Training on VM.    Error: Got unexpected extra arguments (/dir)

### ISSUE THREAD

**Issue by SUPERSHOPxyz** [NVlabs/stylegan3#129]
I have setup up environment.yml on Paperspace Core Virtual Instance. I get everything ready to run and receive this error when I try to finally train:

Error: Got unexpected extra arguments (/DIRECTORY)

I have no clue why this is happening and has not happened every before, but now is hitting the error. I have only tried setting up the environment through manual installs and never YML. 

**MY CODE**
(stylegan3) paperspace@psmtijxvv:~/Desktop/stylegan3$ python train.py --outdir= /home/paperspace/Desktop/tests --cfg=stylegan3-t --data= /home/paperspace/Desktop/data/invert.zip \
> 	--gpus=4 --batch=32 --gamma=32 --batch-gpu=4 --snap=20

Traceback (most recent call last):
  File "/home/paperspace/Desktop/stylegan3/train.py", line 20, in <module>
	from training import training_loop
  File "/home/paperspace/Desktop/stylegan3/training/training_loop.py", line 16, in <module>
	import psutil
ModuleNotFoundError: No module named 'psutil'
(stylegan3) paperspace@psmtijxvv:~/Desktop/stylegan3$
(stylegan3) paperspace@psmtijxvv:~/Desktop/stylegan3$ pip install psutil
Collecting psutil
  Downloading psutil-5.9.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
 	|████████████████████████████████| 280 kB 29.6 MB/s
Installing collected packages: psutil
Successfully installed psutil-5.9.0
(stylegan3) paperspace@psmtijxvv:~/Desktop/stylegan3$ python train.py --outdir= /home/paperspace/Desktop/tests --cfg=stylegan3-t --data= /home/paperspace/Desktop/data/invert.zip 	--gpus=4 --batch=32 --gamma=32 --batch-gpu=4 --snap=20
Usage: train.py [OPTIONS]
Try 'train.py --help' for help.

Error: Got unexpected extra arguments (/home/paperspace/Desktop/tests /home/paperspace/Desktop/data/invert.zip)
(stylegan3) paperspace@psmtijxvv:~/Desktop/stylegan3$

**Expected behavior**
Expected for training to start running.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - pytorch 1.9.0
 - CUDA 11.4
 - NVIDIA driver version 445
 - GPU [2x A100]
 - Docker: No

**Additional context**

**Comment by ZeldaMaster501** [comment]
Remove the space after  --outdir= and   --data=

` python train.py --outdir=/home/paperspace/Desktop/tests --cfg=stylegan3-t --data=/home/paperspace/Desktop/data/invert.zip --gpus=4 --batch=32 --gamma=32 --batch-gpu=4 --snap=20`

**Comment by SUPERSHOPxyz** [comment]
@ZeldaMaster501 Im having trouble with dependencies and the environment setup on a VM. I am still a bit of a newb, wondering if you'd be willing to assist in the setup of the training environment? Happy to pay for your time. If not, no worries!
