### ISSUE TITLE
Conditional generation in visualizer

### ISSUE THREAD

**Issue by jasony93** [NVlabs/stylegan3#131]
visualizer.py has been useful for understanding how my model trained and generates images.
Now, I moved on to training conditional gan, and so far, the training results seem reasonable.
I also tried to load my conditionally trained weight file onto visualizer, but I do not see a class option.
I have been wondering if there is a way to generate images in certain class in visualizer.py.

I appreciate in advance.

**Comment by jasony93** [comment]
I figured it out by myself.
The trick is below.

From viz/renderer.py, 
`for idx, seed in enumerate(all_seeds):
            # idx = 0
            rnd = np.random.RandomState(seed)
            all_zs[idx] = rnd.randn(G.z_dim)
            if G.c_dim > 0:
                # all_cs[idx, rnd.randint(G.c_dim)] = 1
                all_cs[idx, class] = 1`

I replaced rnd.randint(G.c_dim) with label, so that images in certain class are generated.

**Comment by dongyunkim-arch** [comment]
Hi @jasony93 did you manage to train conditional stylegan? I am also working on it, but it is pretty challenging for me. Especially, I want to do multi-label things such as 'hairstyle', 'age', 'race' etc.

**Comment by 49xxy** [comment]
> 你好@jasony93你训练有条件的 stylegan 了吗？我也在努力，但这对我来说非常具有挑战性。特别是，我想做多标签的东西，比如“发型”、“年龄”、“种族”等。

Hi！May I ask if your problem has been solved? How to annotate an image with multiple attributes?

**Comment by jasony93** [comment]
> Hi @jasony93 did you manage to train conditional stylegan? I am also working on it, but it is pretty challenging for me. Especially, I want to do multi-label things such as 'hairstyle', 'age', 'race' etc.

Sorry for the too late reply. I managed to train conditional stylegan, but in my case, it the class was background color, which I think is way easier to train than yours. Did you get it worked out?

**Comment by jasony93** [comment]
> > 你好@jasony93你训练有条件的 stylegan 了吗？我也在努力，但这对我来说非常具有挑战性。特别是，我想做多标签的东西，比如“发型”、“年龄”、“种族”等。
> 
> Hi！May I ask if your problem has been solved? How to annotate an image with multiple attributes?

I was able to train with multiple classes, but my classes are not multiple attributes. I think what you mean by 'multiple attributes' is such as person with blonde hair, brown eyes -> two attributes?

**Comment by 49xxy** [comment]
> > > 你好@jasony93你有什么条件吗？
> > 
> > 
> > 您好！请问您的问题解决了吗？如何注释具有多个属性的图像？
> 
> 我能够训练多个课程，但我的课程不是多个属性。我认为您所说的“多重属性”是指金发，棕色眼睛的人->两个属性？

Yes, your understanding is correct！

**Comment by jasony93** [comment]
> > > > 你好@jasony93你有什么条件吗？
> > > 
> > > 
> > > 您好！请问您的问题解决了吗？如何注释具有多个属性的图像？
> > 
> > 
> > 我能够训练多个课程，但我的课程不是多个属性。我认为您所说的“多重属性”是指金发，棕色眼睛的人->两个属性？
> 
> Yes, your understanding is correct！

This is my theory (You should try by yourself)
I believe multiple attributes is also doable. Let's say you have 2 attributes.
For example, 1 attribute being hair color which can be black, blonde, and brown. Another attribute is gender which can be male or female. In encoded vector form, people with black can be represented as [1, 0, 0, 0, 0].
people with blonde hair = [0, 1, 0, 0, 0]
people with brown hair = [0, 0, 1, 0, 0]
Male = [0, 0, 0, 1, 0]
Female = [0, 0, 0, 0, 1]
If you want to generate males with black hair, then you should mix up corresponding vectors.
=> [1, 0, 0, 1, 0]
Hope this helps.
