### ISSUE TITLE
Can I use a stylegan2-ada model for transfer learning on stylegan3?

### ISSUE THREAD

**Issue by Randy1435** [NVlabs/stylegan3#15]
The title really all says it. I'm wanting to transfer learn a stylegan2-ada model to stylegan3. The dataset will be similar to the dataset of the stylegan2-ada model I trained.

**Comment by jannehellsten** [comment]
I don't think you can transfer learn with stylegan3-t/stylegan3-r configs on top of a stylegan2 model.  

It might work if you use the stylegan2 config with `--cfg=stylegan2`.  But then it's pretty much the same as just using the stylegan2-ada-pytorch code.
