### ISSUE TITLE
How to specify which GPU visualizer.py uses?

### ISSUE THREAD

**Issue by kisenera** [NVlabs/stylegan3#158]

**Comment by trontronicent** [comment]
while the docs dont show a way to select a specific gpu directly on the stylegan python "cli", pytorch does have a way to set a preferred / default gpu:  https://jdhao.github.io/2018/04/02/pytorch-gpu-usage
but seriously, simply entering "how to set cuda / pytorch default gpu" into the google search would have saved you 3 days of waiting for a reply ;)
