### ISSUE TITLE
stuck on evaluating metrics

### ISSUE THREAD

**Issue by eccegallery** [NVlabs/stylegan3#16]
Began training a new GAN last night on a dataset of 512x512 images, and after letting it run overnight I still do not have the 'tick 1' benchmark. I did notice in the readme that it would take a while if only training on 1 GPU (i am training on a single 3090), but 14+ hours before the first benchmark seems long. Do I need to reset my training parameters and start over? (gpus=1, batch=32, gamma=8, batch-gpu=8, snap=5)

**Comment by manoadamro** [comment]
is the GPU actually doing any work? (if you check with afterburner, hwinfo or something you should be able to see the load)
I have had a couple of cases with my 3090 where the gpu has stopped doing anyting but the program just hangs. 
That said, with stylegan2 I never actually got the metrics to work on my 3090 🤔 

I've just started training now, let's see what happens 🤞
