### ISSUE TITLE
Cannot create conditional network

### ISSUE THREAD

**Issue by leona** [NVlabs/stylegan3#161]
I'm having issues creating a conditional network. I've structured the dataset.json like this, using 4 images to test.
```
{
   "labels":[
      ["561462394.png",0],
      ["638577443.png",1],
      ["642091536.png",1],
      ["691798228.png",0]
   ]
}
```
Then I use the dataset tool
```
python dataset_tool.py --source=/scratch/input-test --dest=/scratch/input-scaled/test-128x128.zip \
    --resolution=128x128
```
I've unzipped test-128x128.zip and confirmed the dataset.json is there with the correct paths and labels.
Then I start training
```
python train.py --outdir=/scratch/training-runs --cfg=stylegan3-t --data=/scratch/input-scaled/test-128x128.zip \
  --gpus=2 --batch=32 --gamma=2 --snap=25 --kimg=5000 --mirror=1 --nobench 0
```
And I get the following output, showing that the labels weren't picked up
```
Dataset labels:      False
Label shape: [0]
```

Not sure what I've missed if anyone has ideas.

**Comment by GHBTM** [comment]
@leona, what was the solution here?  I am training a conditional model as well and would love to keep an eye out for obstacles.

**Comment by 0aakitur** [comment]
> @leona, what was the solution here? I am training a conditional model as well and would love to keep an eye out for obstacles.

To train a conditional network along with the training command, one needs to provide `--cond=True`; as mentioned [here](https://github.com/NVlabs/stylegan3/blob/main/docs/train-help.txt)

Hope this helps :)
