### ISSUE TITLE
How to change the image_snapshot_ticks ??

### ISSUE THREAD

**Issue by kantenboki** [NVlabs/stylegan3#164]
I want to change image_snapshot_ticks=50 to 10.

So, I changed the image_snapshot_ticks in training_loop.py,

but when I look at trainig_options.json, the number have not changed.

How can I change the image_snapshot_ticks?

**Comment by PDillis** [comment]
`image_snapshot_ticks` will use whatever value `--snap` has (as seeh [here](https://github.com/NVlabs/stylegan3/blob/407db86e6fe432540a22515310188288687858fa/train.py#L219)), so if you don't change it, it will [use the default value of `50`](https://github.com/NVlabs/stylegan3/blob/407db86e6fe432540a22515310188288687858fa/train.py#L157). So, if you want to save both the model and the image snapshots more often, you must add `--snap=10`.

Alternatively, you can decouple them and e.g. save the image snapshots more often than the network snapshots, as the former will indicate you better how training is doing and you can save it as often as you want compared to the model snapshots. [This is what I do in my StyleGAN3 repository](https://github.com/PDillis/stylegan3-fun), for example, so I can save the image snapshots every tick ([`--img-snap=1`](https://github.com/PDillis/stylegan3-fun/blob/97f7e67acb5f6421c6f895033d32cf0b04b26c91/train.py#L162)), and save the model every 10 ticks ([`--snap=10`](https://github.com/PDillis/stylegan3-fun/blob/97f7e67acb5f6421c6f895033d32cf0b04b26c91/train.py#L161)).
