### ISSUE TITLE
imageio dependency missing in Dockerfile

### ISSUE THREAD

**Issue by ryan-cranfill** [NVlabs/stylegan3#17]
**Describe the bug**
Hi there, excited to give StyleGAN3 a go! I built the docker image locally using `docker build --tag stylegan3 .`. When I went to use the image, I got this error:

`Traceback (most recent call last):
  File "gen_video.py", line 18, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'`

**I was able to fix this error and get it running** by adding `imageio` as a dependency to the `pip install` command in the dockerfile (https://github.com/NVlabs/stylegan3/blob/aee7486b11ba7404d8487d91a932131b90464be3/Dockerfile#L14) so it now reads: `RUN pip install imageio imageio-ffmpeg==0.4.4 pyspng==0.1.0`

**To Reproduce**
1. In root directory, run command `docker run --gpus all -it --rm --user $(id -u):$(id -g) \
    -v `pwd`:/scratch --workdir /scratch -e HOME=/scratch \
    stylegan3 \
    python gen_video.py --output=lerp.mp4 --trunc=1 --seeds=0-31 --grid=4x2 \
    --network=https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-r-afhqv2-512x512.pkl`
2. See error `Traceback (most recent call last):
  File "gen_video.py", line 18, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'`

**Expected behavior**
A video getting generated :) 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04.5 LTS
 - CUDA 11.2
 - NVIDIA driver version: 460.27.04
 - GPU: RTX 3090
 - Docker: did you use Docker? Yep, the version in the Dockerfile: nvcr.io/nvidia/pytorch:21.08-py3

**Comment by nurpax** [comment]
Thanks for the report.  You're right, imageio should be included.  Looks like I missed this in my testing.  A fix is incoming.
