### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by JiaweiShiCV** [NVlabs/stylegan3#18]
How long does it take to train with 8 GPUs for the two configurations of stylegan3?

**Comment by Afanas666** [comment]
Понятия не имею, я лишь учусь.

**Comment by Randy1435** [comment]
Depends on the dataset, your GPU, which model you're transfer learning, etc etc

**Comment by JiaweiShiCV** [comment]
I want to know the traning time consumed of configs for DGX A100 or V100 (8 GPUs) on FFHQ-U.

**Comment by Randy1435** [comment]
You should find this somewhere in this repo.

**Comment by jannehellsten** [comment]
There's a separate doc for training configurations with a lot of detail on training time: https://github.com/NVlabs/stylegan3/blob/main/docs/configs.md#total-training-time

I believe the stylegan3-t config at 1024x1024 would be roughly 5 days 19 hours on A100 DGX (8 GPUs).
