### ISSUE TITLE
onnx convert

### ISSUE THREAD

**Issue by puppy9207** [NVlabs/stylegan3#19]
Is there a problem converting to onnx? In the case of stylegan2, the problem of converting to onnx has not been solved yet. I'm worried that stylegan3 will have the same problem.

**Comment by farzanehnakhaee70** [comment]
Is there any updates on this?

**Comment by SkyTNT** [comment]
Hello, this is my notebook, it can convert stylegan2 model to onnx. https://www.kaggle.com/skytnt/convert-model/notebook

**Comment by tianmaxingkong12** [comment]
> Hello, this is my notebook, it can convert stylegan2 model to onnx. https://www.kaggle.com/skytnt/convert-model/notebook

hello, when I use your code,I found such error "RuntimeError: ONNX export only p-norms with p of 1 or 2" .How do I fix it? Thank you
