### ISSUE TITLE
runerror: model don't match with net

### ISSUE THREAD

**Issue by vastyao** [NVlabs/stylegan3#23]
**Describe the bug**
load the *.pkl don't match the model

**To Reproduce**
1. python train.py --outdir=~/training-runs --cfg=stylegan3-t --data={dir}.zip \
    --gpus=1 --batch=32 --gamma=6.6 --mirror=1 --kimg=5000 --snap=5 \
    --resume={dir}/stylegan3-t-ffhqu-256x256.pkl
2. RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 1

**Comment by Maxim-Durand** [comment]
I run in exactly the same problem.
Steps to reproduce:
`
> python dataset_tool.py --source=/notebooks/raw_images/ --dest=/notebooks/dataset_512/ --resolution='512x512' --transform=center-crop

> python train.py --outdir=/notebooks/training-runs --cfg=stylegan3-r --data=/notebooks/dataset_512 \
    --gpus=1 --batch=16 --gamma=6 --mirror=1 --kimg=5000 --snap=5 \
        --resume=https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-r-metfacesu-1024x1024.pkl
`


Full stack trace:

  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 96, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/notebooks/stylegan3/training/training_loop.py", line 162, in training_loop
    misc.copy_params_and_buffers(resume_data[name], module, require_all=False)
  File "/notebooks/stylegan3/torch_utils/misc.py", line 162, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (24) must match the size of tensor b (12) at non-singleton dimension 0

**Comment by jannehellsten** [comment]
Looks like a resolution mismatch?  Trying to use 512x512 resolution image to transfer learn a 1024x1024 model?

**Comment by georgi** [comment]
I think this issue should be reopened as the behaviour is very unexpected and incorrect.

Following should work but throws an error.

```
python train.py --outdir=training-runs --data=/home/mm/dev/toons/img --cfg=stylegan3-t --gpus=1 --batch=32 --gamma=2 --batch-gpu=8 --snap=10 --metrics=none --resume=stylegan3-t-ffhqu-256x256.pkl
....
Num images:  5580
Image shape: [3, 256, 256]
Label shape: [0]

Constructing networks...
Resuming from "stylegan3-t-ffhqu-256x256.pkl"
Traceback (most recent call last):
  File "/home/mm/dev/stylegan3/train.py", line 286, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/conda/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mm/dev/stylegan3/train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/home/mm/dev/stylegan3/train.py", line 96, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/home/mm/dev/stylegan3/train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/home/mm/dev/stylegan3/training/training_loop.py", line 162, in training_loop
    misc.copy_params_and_buffers(resume_data[name], module, require_all=False)
  File "/home/mm/dev/stylegan3/torch_utils/misc.py", line 162, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 1

```

**Comment by justinpinkney** [comment]
@georgi you need to add `--cbase=16384` when resuming from that 256 model

**Comment by MoemaMike** [comment]
I am not sure but the issue might be related to --cfg=stylegan3-t  . I had trained models on --cfg=stylegan3-r successfully for some time and then tried to resume training with --cfg=stylegan3-t and i encountered this exact runtime error . It was the only thing i changed.

**Comment by sh0gg0th** [comment]
Facing the same problem with both `stylegan3-r-ffhqu-256x256.pkl` and `stylegan3-t-ffhqu-256x256.pkl`, setting `-cbase=16384` makes it work.

**Comment by BenjiKCF** [comment]
> Facing the same problem here While the following works with a 256x256 images `python train.py --outdir=training-runs-all --cfg=stylegan3-t --data=all_cls/all_cls256.zip --gpus=1 --batch=32 --gamma=2 --batch-gpu=32 --cbase=16384 --snap=10 --mirror=1 --cond=True --aug=ada` The below doesnt work `python train.py --outdir=training-runs-all --cfg=stylegan3-t --data=all_cls/all_cls256.zip --gpus=1 --batch=32 --gamma=2 --batch-gpu=32 --cbase=16384 --snap=10 --mirror=1 --cond=True --aug=ada --resume=https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-t-ffhqu-256x256.pkl` With a `RuntimeError: The size of tensor a (1024) must match the size of tensor b (512) at non-singleton dimension 1` It seems that the resume model does not work with --cond=True?

In the paper "Training Generative Adversarial Networks with Limited Data", appendix CIFAR-10, it stated that for class conditional image generation, the model will concatenate the class embedding (512-dim) to the latent code. This is why the shape is different from the pretrained model.

**Comment by GTziolas** [comment]
Can anyone provide any insight as to how we can resume training the pretrained models with --cond=True?

**Comment by ghost** [comment]
> @georgi you need to add `--cbase=16384` when resuming from that 256 model

I am wondering what role dose '--cbase' play, do you know it?

**Comment by shanaka95** [comment]
> > @georgi you need to add `--cbase=16384` when resuming from that 256 model
> 
> I am wondering what role dose '--cbase' play, do you know it?

I have the same question
