### ISSUE TITLE
Could not convert weights to .pt

### ISSUE THREAD

**Issue by forkbabu** [NVlabs/stylegan3#3]

**Comment by forkbabu** [comment]
Same as #4 
cc: @jannehellsten @nurpax

**Comment by SerdarHelli** [comment]
with dnnlib.util.open_url(network_pkl) as f:
torch.save(legacy.load_network_pkl(f)['G_ema'].state_dict(), 'weight.pt')

After this one , How am I gonna load pt file ?
this doesnt work 
PATH="model.pt"
G = torch.load(PATH)
G.eval()
G.to(device)
