### ISSUE TITLE
Why is 1024-model-file smaller than 512-model-file?

### ISSUE THREAD

**Issue by wodsoe** [NVlabs/stylegan3#33]
Why is 1024-model-file smaller than 512-model-file?
![1](https://user-images.githubusercontent.com/40934627/137744574-c21ae51f-1e2d-42c6-a1dd-3e1774f479ce.png)

**Comment by hmdolatabadi** [comment]
The paper says: "Note that [unlike StyleGAN2] the number of layers is now a free parameter that does not directly depend on the output resolution." So the file sizes should be more or less in the same range, which seem to be.

**Comment by PeterL1n** [comment]
The paper says they use exactly N=14 layers for all resolutions, so 512 models and 1024 models have the same number of convolutions. However, the 512 model's cutoff frequency grows only to fc=256 while 1024's cutoff frequency grows to fc=512 for the last 2 critical sampling layers. The number of channels is determined by the inverse of fc. So 1024 models actually have fewer channels than 512 models in those layers.

**Comment by wodsoe** [comment]
I see.Thank you @PeterL1n
