### ISSUE TITLE
filtered_lrelu_plugin problem

### ISSUE THREAD

**Issue by k-l-lambda** [NVlabs/stylegan3#38]
At first I got:

> filtered_lrelu.cpp(147): error C4984: 'if constexpr' is a C++17 language extension

It's from this line:

> if constexpr (sizeof(scalar_t) <= 4)

sizeof scalar_t is either less/equal 4, or greater than 4, so I tried to remove this condition sentence.

But then I got:

> filtered_lrelu_plugin.pyd : fatal error LNK1120: 6 unresolved externals

There are 6 unresolved symbols about template function 'choose_filtered_lrelu_kernel'. Maybe scalar_t is greater than 4, so I removed all the code referencing 'choose_filtered_lrelu_kernel'.

But then I failed at this line:

filtered_lrelu.cpp(160)
>     TORCH_CHECK(spec.exec, "internal error - CUDA kernel not found") // This should not happen because we tested earlier that kernel exists.

My environment is Windows 10, python 3.8, CUDA 11.1 (cudnn-11.1-windows-x64-v8.0.5.39), torch 1.9.0.

**Comment by k-l-lambda** [comment]
![image](https://user-images.githubusercontent.com/11451724/137886019-84f5937f-7b3c-4c31-83a4-7a87dcbc1b04.png)

Good luck for you.

**Comment by flybrotherhoi** [comment]
Very Nice!!! I just met the same problem. Solved by your solution.

**Comment by mxl1990** [comment]
I use your modification, it works for me, Thanks!
I also find another way to solve this problem without modify code.
Install VS2019 rather than VS2017.
