### ISSUE TITLE
Is it possible to control the scale of the output?

### ISSUE THREAD

**Issue by backpass** [NVlabs/stylegan3#62]
Hi, 

I am tweaking with the affine transformations for the first layer at: https://github.com/NVlabs/stylegan3/blob/a5a69f58294509598714d1e88c9646c3d7c6ec94/training/networks_stylegan3.py#L205
I am wondering if it is possible to control the scale as well as translation and rotation? I have tried adding scale but the results are bad. If the scale is too big, then face collapses into the point or shred all over the place with smaller scale. In particular, I am interested in generating the images with wide crop, so that the whole head(with hair) and neck is visible.

Would be very grateful for your help or any commentaries.

**Comment by PDillis** [comment]
I don't think the affine transform is the tool you need for this, as the network wasn't trained to be invariant to *any* affine transformation, only to translation and rotation. For example, if you also add shear and scale, you can get interesting outputs, but the network shouldn't be invariant to these transforms, as that wouldn't make much sense; some examples:

![00003](https://user-images.githubusercontent.com/24496178/140912409-81763b2c-3b20-434d-ac71-e95d118b071a.png)
![00004](https://user-images.githubusercontent.com/24496178/140912415-cb0daa4c-9e6d-4313-9bfa-cda720d0c94b.png)

I must note that zoom-in does work better than zoom-out, however, this is perhaps not what you look for; an example:

https://user-images.githubusercontent.com/24496178/140913582-b7ec0746-bf4a-48d9-951f-946b3ac78167.mp4

The usual suspect for what you want would be the learned Fourier features. You can find these at the `forward` of the [`SynthesisInput`](https://github.com/NVlabs/stylegan3/blob/a5a69f58294509598714d1e88c9646c3d7c6ec94/training/networks_stylegan3.py#L198). There are a lot of parameters to test here, so I hope one does the job, but I have my suspicions more on `self.bandwidth`

**Comment by backpass** [comment]
Thank you for the response @PDillis !

If I understand it correctly, the Fourier features are generated randomly and are changed only via learned affine and the `self.weight` parameter. So I can only play with the input parameters: `self.bandwidth` and `self.sample_rate`. Is it correct?

May you add more context on this please, as I am not really an expert in Fourier theory.
What are particularly important parameters to test here? And also why bandwidth is important to play with?

**Comment by backpass** [comment]
Seems like changing sampling rate did the thing. In paper they are writing: 

> For now, we choose to employ critical sampling and set the filter cutoff fc = s/2, i.e., exactly at the bandlimit, and transition band half-width fh = (√ 2 − 1)(s/2). Recall that sampling rate s equals the width of the canvas in pixel.

They do not use padding but the pixel margin is used instead which is cropped out at the end, making sampling rate lower means part of the canvas comes through. They are doing it through affine transform: https://github.com/NVlabs/stylegan3/blob/a5a69f58294509598714d1e88c9646c3d7c6ec94/training/networks_stylegan3.py#L225

Band-limit does not affect the result, but if it is larger than sampling rate / 2 - the result is vanishing out. It may have something to do with Nyquist rate.

There are some examples: 
![seed0012](https://user-images.githubusercontent.com/74189151/140969805-005dc2fb-59e1-4233-91c7-b08f2521fe4a.png)
![seed0018](https://user-images.githubusercontent.com/74189151/140969810-14e0ff02-36dc-48d2-940b-c5269e7890d9.png)

However, in some cases the head is not in the center and the top or the bottom intersect with the image boundary. @PDillis do you know if it is possible to set the translation parameters so that nose is always in the center?
 
![seed0007](https://user-images.githubusercontent.com/74189151/140970424-fe798242-8547-4ff7-b1bf-abd6c83ba150.png)

**Comment by PDillis** [comment]
That's great that you figured it out! Could you share the changes you did to get those outputs?

Centering the output is also easy: you anchor the latent space to `w_avg` (thanks to @RiversHaveWings and @nshepperd1):

```python
if hasattr(G.synthesis, 'input'):
        shift = G.synthesis.input.affine(G.mapping.w_avg.unsqueeze(0))
        G.synthesis.input.affine.bias.data.add_(shift.squeeze(0))
        G.synthesis.input.affine.weight.data.zero_()
```

The `if` is important so you don't try anything wonky with e.g. StyleGAN2 Generators. The `shift` could be anything, so long as it has the correct shape, so it's another thing to play with!

Since it's used a lot, I saved it in a [utils folder in my fork](https://github.com/PDillis/stylegan3-fun/blob/918f1d948dea29768b7c49232dc703e68449070a/torch_utils/gen_utils.py#L320), which I recommend you also do. It's particularly useful for projection so that the space doesn't move around and the network can more easily project the target image (but it's also nice to use when generating images or doing [interpolations](https://twitter.com/PDillis/status/1448254764593123330?s=20)).

**Comment by backpass** [comment]
I have changed `self.sampling_rate=14`, the default is 16.
I also used manually found params for affine transform to center the faces. These are changes in `self.forward` starting from [here](https://github.com/NVlabs/stylegan3/blob/a5a69f58294509598714d1e88c9646c3d7c6ec94/training/networks_stylegan3.py#L205)
```
t = self.affine(w) # t = (r_c, r_s, t_x, t_y)
t = t / t[:, :2].norm(dim=1, keepdim=True) # t' = (r'_c, r'_s, t'_x, t'_y)
m_r = torch.eye(3, device=w.device).unsqueeze(0).repeat([w.shape[0], 1, 1]) # Inverse rotation wrt. resulting image
angle = 0.0
rc, rs = np.cos(angle / 360.0 * np.pi * 2), np.sin(angle / 360.0 * np.pi * 2)
tx, ty = -0.4, 0.15
m_r[:, 0, 0] = rc  # r'_c
m_r[:, 0, 1] = -rs # r'_s
m_r[:, 1, 0] = rs  # r'_s
m_r[:, 1, 1] = rc * s  # r'_c
m_t = torch.eye(3, device=w.device).unsqueeze(0).repeat([w.shape[0], 1, 1]) # Inverse translation wrt. resulting image.
m_t[:, 0, 2] = -tx # t'_x
m_t[:, 1, 2] = -ty # t'_y
```
Thank you for your advice, I have tried the w_avg as well, it seems to have the same logic and the results are comparable with my manually found. But the solution is more general and I think it is better to use it instead.
