### ISSUE TITLE
How to save specific tick state in a file and resume training from that file?

### ISSUE THREAD

**Issue by mah1212** [NVlabs/stylegan3#67]
How can I save a specific tick state in a file? For instance, I want to save every 100 ticks in a file. 
And how can I resume training from that file?

**Comment by PDillis** [comment]
When you run `train.py`, one of the options you have is `--snap`, which is how often (in ticks) you will save snapshots of your trained model, so you can set `--snap=100`. To resume from this tick, they will be saved as `network-snapshot-000100.pkl`, for example, so again when you run `train.py`, you use `--resume=/path/to/network-snapshot-000100.pkl`, where you input the actual path to that `.pkl` file.

**Comment by mah1212** [comment]
@PDillis Thank you so much
