### ISSUE TITLE
Transfer learning and image rotation

### ISSUE THREAD

**Issue by nerdyrodent** [NVlabs/stylegan3#7]
Not sure if looks right, but when trying to resume from a previous stylegan2 pkl, I got the initial fakes looking as if they were starting from scratch:
![fakes000000](https://user-images.githubusercontent.com/74688049/136924743-5681d52e-aa08-4227-aa35-063cddf7fb1e.jpg)

After a while they do start to take shape, just rotated:
![fakes000256](https://user-images.githubusercontent.com/74688049/136924741-63b2116f-b3fc-4599-8819-9b8f0e8e744f.jpg)

All normal?

I also tried resuming from a couple of the listed stylegan3 pkls, but got tensor errors a bit like if the image sizes were different (e.g. "The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 0")

Any and all suggestions gratefully received!

**Comment by jannehellsten** [comment]
Please include the full command line you used or attach `training_options.json` from your run.  I'm assuming you tried to train on top of a stylegan2 model but used one of the new configs `stylegan3-t` or `stylegan3-r` to train it.  This won't work.  If you anyway go ahead and do this, the result will be pretty close to just training from scratch.

As for the tensor size problem: it looks like your dataset resolution does not match with the model resolution.  Can you spell out what exact stylegan3 model you tried with and what resolution is your dataset?  (It looks like the error handling for resolution could be improved in our code to give a better error message.)

**Comment by nerdyrodent** [comment]
Thanks for the update. Training from scratch is working fine, so I'm doing that :)

Image Resolution: 256
Resume tested from:
* stylegan3-t-ffhqu-256x256.pkl
* stylegan3-r-ffhqu-256x256.pkl

I've tried resuming from my network snapshots, and they work OK.
