### ISSUE TITLE
Clarification on allow_tf32 flag

### ISSUE THREAD

**Issue by vanga** [NVlabs/stylegan3#85]
Hi,

I would like to know if there is a specific reason on why allow_tf32 flag is not exposed as cli stylegan3 unlike [stylegan3-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/d4b2afe9c27e3c305b721bc886d2cb5229458eba/train.py#L64).
`Improves numerical accuracy.` This is what is commented while setting it to false 

I read that to take full benefit of A100s, we need to set this flag. Considering that the usage of this in SG3 repo seems to be different from SG3-ada-pytorch, I would like to know if this is intentional or if there will be any consequences on the model performance if I were to set this flag to True manually.

Thanks in advance.

**Comment by nurpax** [comment]
(I think you meant stylegan2-ada-pytorch, not stylegan3..)

The StyleGAN3 model's large convolution layers are manually tuned to use fp16 where it matters.  I don't expect there to be a large difference in allowing TF32.

If you're curious how it affects performance, you can benchmark it yourself by changing the tf32 arguments here:

https://github.com/NVlabs/stylegan3/blob/main/training/training_loop.py#L130

If you force all the layers to use fp32 and then enable tf32, you should see a decent performance increase.  (But as per my own benchmarking, still slower than the current fp16-optimized version.)

**Comment by vanga** [comment]
Thanks @nurpax . Yes, I meant stylegan2-ada-pytorch.
I actually went ahead and changed L130,131 to True to see what it does. I only see 3-4% improvement. I guess I don't need to bother about it.
Your explanation explains why there is no significant change.

Thanks for the quick confirmation.
