### ISSUE TITLE
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 1, -1, 1, 1] because the unspecified dimension size -1 can be any value and is ambiguous

### ISSUE THREAD

**Issue by wodsoe** [NVlabs/stylegan3#87]
Error while training stylegan2 if set batch-gpu=1

python train.py --cfg=stylegan2  --gpus=1 --batch=32 --batch-gpu=1 --mbstd-group=1 --gamma=2

networks_stylegan2.py", line 61, in modulated_conv2d
    w = w * styles.reshape(batch_size, 1, -1, 1, 1) # [NOIkk]
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 1, -1, 1, 1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by PDillis** [comment]
Do you mean that there's an error if you try to train with a batch size of 1, or that you get that error when trying that command? If the latter, then I suggest setting `--batch-gpu=32`, since `--batch=32` and you have only one gpu.

**Comment by wodsoe** [comment]
There's an error if training stylegan2 with a batch size of 1.You can try @PDillis
