### ISSUE TITLE
Using Compressed Images in Dataset

### ISSUE THREAD

**Issue by jallbrit** [NVlabs/stylegan3#93]
The [README](https://github.com/NVlabs/stylegan3#preparing-datasets) states:

> Datasets are stored as uncompressed ZIP archives containing uncompressed PNG files and a metadata file dataset.json for labels. Custom datasets can be created from a folder containing images; see python dataset_tool.py --help for more information. ...

My folder of `.jpg`s got expanded from `3.9G` to `76G` when I ran them through `dataset-tool.py`. I use a GPU rental service to train StyleGAN, so this basically renders my dataset unusable, because it takes too long to send 76G over the network to the GPU-connected server. I could, however, feasibly send the `jpg`'s over and decompress on my rented machine. This is my solution for now.

My question is: what happens if you try to train using compressed `.jpg`s, or even compressed `.png`s? Using `pngquant` I was able to compress the resultant `.png`s by 86%, which would make transporting this dataset *so* much easier.

The README also states:

>  ...Alternatively, the folder can also be used directly as a dataset, without running it through dataset_tool.py first, but doing so may lead to suboptimal performance.

Hmm. So, could I run `train.py` using compressed images for a small performance price? How "suboptimal" is the performance if you use compressed `.jpg`s or `.png`s? Are we talking a 2% training speed decrease, or a 15% training speed decrease? Can anybody quantify that?

**Comment by vsemecky** [comment]
Yes you can use compressed images. No problem. In fact I always use compressed images (JPG with 98-100% quality). The reduction in quality is not measurable and the size still much smaller.

**Comment by jallbrit** [comment]
@vsemecky thank you!
